package kb

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"strings"
)

// The four kb comment shapes (design §8). Any other comment opening with the kb prefix
// is a check failure.
const (
	generatedPrefix = "<!-- kb:generated "
	generatedSuffix = " — regenerated by make gen-kb; edit the sources, not this file -->"
	hashPrefix      = "<!-- kb:hash "
	kbCommentPrefix = "<!-- kb:"
)

var (
	fragmentOpenRE = regexp.MustCompile(`<!-- kb:(\w+) -->`)
	generatedRE    = regexp.MustCompile(`^<!-- kb:generated ([0-9a-f]{16}) — regenerated by make gen-kb; edit the sources, not this file -->$`)
	hashLineRE     = regexp.MustCompile(`^<!-- kb:hash ([0-9a-f]{16}) -->$`)
	kbCommentRE    = regexp.MustCompile(`<!-- /?kb:[^>]*-->`)
)

// fragmentNames are the fragment blocks a hand-written CLAUDE.md may carry.
var fragmentNames = []string{"features", "trailer"}

// bodyHash is the first sixteen hex digits of the body's sha256.
func bodyHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

// WrapGenerated prefixes body with its kb:generated header. A body that opens with a
// frontmatter block (a rules file) gets the header directly after that block instead,
// because Claude Code reads frontmatter from byte zero.
func WrapGenerated(body string) string {
	header := generatedPrefix + bodyHash(body) + generatedSuffix + "\n"
	if end := frontmatterEnd(body); end > 0 {
		return body[:end] + header + body[end:]
	}
	return header + body
}

// frontmatterEnd returns the byte offset just past a leading frontmatter block's closing
// line, or 0 when the text has none.
func frontmatterEnd(text string) int {
	if !strings.HasPrefix(text, "---\n") {
		return 0
	}
	idx := strings.Index(text[4:], "\n---\n")
	if idx == -1 {
		return 0
	}
	return 4 + idx + len("\n---\n")
}

// SplitGenerated finds the kb:generated header (line one, or the first line after a
// leading frontmatter block) and returns its hash and the content without that line.
// ok is false when there is no header.
func SplitGenerated(content string) (hash, body string, ok bool) {
	start := frontmatterEnd(content)
	rest := content[start:]
	nl := strings.IndexByte(rest, '\n')
	if nl == -1 {
		return "", "", false
	}
	m := generatedRE.FindStringSubmatch(rest[:nl])
	if m == nil {
		return "", "", false
	}
	return m[1], content[:start] + rest[nl+1:], true
}

// GeneratedState classifies a generated file on disk against its regenerated content.
type GeneratedState int

const (
	// GeneratedFresh means disk equals the regenerated content.
	GeneratedFresh GeneratedState = iota
	// GeneratedStale means the header hash matches its body but the sources moved on.
	GeneratedStale
	// GeneratedHandEdited means the body no longer matches its own header hash, or the
	// header is missing.
	GeneratedHandEdited
)

// ClassifyGenerated applies design K6: a missing header or a body that no longer matches
// its hash is a hand edit; a self-consistent file that differs from want is stale.
func ClassifyGenerated(disk, want string) GeneratedState {
	if disk == want {
		return GeneratedFresh
	}
	hash, body, ok := SplitGenerated(disk)
	if !ok || bodyHash(body) != hash {
		return GeneratedHandEdited
	}
	return GeneratedStale
}

// wrapFragment renders a fragment value: a leading newline, the hash line covering the
// rest, then body and a trailing newline — the value owns its own line breaks so the
// markers never land on a table row.
func wrapFragment(body string) string {
	inner := body + "\n"
	return "\n" + hashPrefix + bodyHash(inner) + " -->\n" + inner
}

// classifyFragment applies K6 to one fragment's on-disk inner value.
func classifyFragment(disk, want string) GeneratedState {
	if disk == want {
		return GeneratedFresh
	}
	lines := strings.SplitN(disk, "\n", 3)
	if len(lines) < 3 || lines[0] != "" {
		return GeneratedHandEdited
	}
	m := hashLineRE.FindStringSubmatch(lines[1])
	if m == nil || bodyHash(lines[2]) != m[1] {
		return GeneratedHandEdited
	}
	return GeneratedStale
}

// ApplyFragments replaces every named kb fragment block in content with frags[name],
// scanning left to right so blocks cannot swallow each other (the versions tool's
// machinery under the kb namespace). count is the number of blocks replaced.
func ApplyFragments(content string, frags map[string]string) (string, int, error) {
	var b strings.Builder
	count := 0
	rest := content
	consumedTotal := 0
	for {
		loc := fragmentOpenRE.FindStringSubmatchIndex(rest)
		if loc == nil {
			b.WriteString(rest)
			break
		}
		name := rest[loc[2]:loc[3]]
		openEnd := loc[1]
		closer := "<!-- /kb:" + name + " -->"
		closeIdx := strings.Index(rest[openEnd:], closer)
		if closeIdx == -1 {
			return "", 0, fmt.Errorf("fragment %q at offset %d has no matching closing marker", name, consumedTotal+loc[0])
		}
		val, ok := frags[name]
		if !ok {
			return "", 0, fmt.Errorf("unknown fragment name %q at offset %d (want %s)", name, consumedTotal+loc[0], strings.Join(fragmentNames, " or "))
		}
		b.WriteString(rest[:loc[0]])
		b.WriteString("<!-- kb:" + name + " -->")
		b.WriteString(val)
		b.WriteString(closer)
		count++
		consumed := openEnd + closeIdx + len(closer)
		consumedTotal += consumed
		rest = rest[consumed:]
	}
	return b.String(), count, nil
}

// fragmentBlock is one fragment found in a hand-written file.
type fragmentBlock struct {
	Name  string
	Inner string
	Line  int
}

// findFragments lists the fragment blocks in content without rendering them.
func findFragments(content string) ([]fragmentBlock, error) {
	var out []fragmentBlock
	rest := content
	consumedTotal := 0
	for {
		loc := fragmentOpenRE.FindStringSubmatchIndex(rest)
		if loc == nil {
			return out, nil
		}
		name := rest[loc[2]:loc[3]]
		closer := "<!-- /kb:" + name + " -->"
		closeIdx := strings.Index(rest[loc[1]:], closer)
		if closeIdx == -1 {
			return nil, fmt.Errorf("fragment %q at offset %d has no matching closing marker", name, consumedTotal+loc[0])
		}
		out = append(out, fragmentBlock{
			Name:  name,
			Inner: rest[loc[1] : loc[1]+closeIdx],
			Line:  1 + strings.Count(content[:consumedTotal+loc[0]], "\n"),
		})
		consumed := loc[1] + closeIdx + len(closer)
		consumedTotal += consumed
		rest = rest[consumed:]
	}
}

// stripFragments removes every fragment block, markers included, for word counting.
func stripFragments(content string) string {
	blocks, err := findFragments(content)
	if err != nil {
		return content
	}
	out := content
	for _, blk := range blocks {
		full := "<!-- kb:" + blk.Name + " -->" + blk.Inner + "<!-- /kb:" + blk.Name + " -->"
		out = strings.Replace(out, full, "", 1)
	}
	return out
}

// recognisedKBComment reports whether a kb comment is one of the four shapes (or a
// fragment closer).
func recognisedKBComment(c string) bool {
	if generatedRE.MatchString(c) || hashLineRE.MatchString(c) || anchorRE.MatchString(c) {
		return true
	}
	for _, name := range fragmentNames {
		if c == "<!-- kb:"+name+" -->" || c == "<!-- /kb:"+name+" -->" {
			return true
		}
	}
	return false
}
