package kb

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestApplyFragments_ReplacesEachNamedKBBlockAndErrorsOnUnknownOrUnclosed(t *testing.T) {
	frags := map[string]string{"features": "F", "trailer": "T"}
	in := "a <!-- kb:features -->old<!-- /kb:features --> b <!-- kb:trailer -->\nold\n<!-- /kb:trailer --> c"
	out, n, err := ApplyFragments(in, frags)
	require.NoError(t, err)
	assert.Equal(t, 2, n)
	assert.Equal(t, "a <!-- kb:features -->F<!-- /kb:features --> b <!-- kb:trailer -->T<!-- /kb:trailer --> c", out)

	_, _, err = ApplyFragments("x <!-- kb:features -->never closed", frags)
	require.EqualError(t, err, `fragment "features" at offset 2 has no matching closing marker`)

	_, _, err = ApplyFragments("<!-- kb:index -->x<!-- /kb:index -->", frags)
	require.EqualError(t, err, `unknown fragment name "index" at offset 0 (want features or trailer)`)

	out, n, err = ApplyFragments("no markers here", frags)
	require.NoError(t, err)
	assert.Equal(t, 0, n)
	assert.Equal(t, "no markers here", out)
}

func TestApplyFragments_LeavesVersionsMarkersUntouched(t *testing.T) {
	in := "| <!-- versions:range -->2.1.246–2.1.267<!-- /versions:range --> | <!-- kb:features -->old<!-- /kb:features --> |"
	out, n, err := ApplyFragments(in, map[string]string{"features": "new"})
	require.NoError(t, err)
	assert.Equal(t, 1, n)
	assert.Equal(t, "| <!-- versions:range -->2.1.246–2.1.267<!-- /versions:range --> | <!-- kb:features -->new<!-- /kb:features --> |", out)
}

func TestSplitGenerated_DistinguishesFreshStaleAndHandEdited(t *testing.T) {
	want := WrapGenerated("# Title\n\nbody\n")
	hash, body, ok := SplitGenerated(want)
	require.True(t, ok)
	assert.Equal(t, "# Title\n\nbody\n", body)
	assert.Equal(t, bodyHash(body), hash)
	assert.True(t, strings.HasPrefix(want, "<!-- kb:generated "+hash+" — regenerated by make gen-kb; edit the sources, not this file -->\n"))

	older := WrapGenerated("# Title\n\nolder body\n")
	cases := []struct {
		name string
		disk string
		want GeneratedState
	}{
		{"identical", want, GeneratedFresh},
		{"self-consistent but different sources", older, GeneratedStale},
		{"body edited under the same header", strings.Replace(want, "body", "edited", 1), GeneratedHandEdited},
		{"header missing", "# Title\n\nbody\n", GeneratedHandEdited},
		{"header hash mangled", strings.Replace(want, hash, "0000000000000000", 1), GeneratedHandEdited},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, ClassifyGenerated(tc.disk, want))
		})
	}
}

func TestWrapGenerated_PutsTheHeaderAfterALeadingFrontmatterBlock(t *testing.T) {
	body := "---\npaths:\n  - \"internal/**\"\n---\n# f\n"
	out := WrapGenerated(body)
	assert.True(t, strings.HasPrefix(out, "---\npaths:\n"), "frontmatter must stay at byte zero for Claude Code")
	lines := strings.Split(out, "\n")
	assert.True(t, strings.HasPrefix(lines[4], "<!-- kb:generated "), out)
	hash, got, ok := SplitGenerated(out)
	require.True(t, ok)
	assert.Equal(t, body, got)
	assert.Equal(t, bodyHash(body), hash)
	assert.Equal(t, GeneratedFresh, ClassifyGenerated(out, out))
	assert.Equal(t, GeneratedHandEdited, ClassifyGenerated(strings.Replace(out, "internal", "web", 1), out),
		"editing the frontmatter is a hand edit because the hash covers it")
}

func TestClassifyFragment_DistinguishesFreshStaleAndHandEdited(t *testing.T) {
	want := wrapFragment("row one\nrow two")
	older := wrapFragment("row one")
	assert.Equal(t, GeneratedFresh, classifyFragment(want, want))
	assert.Equal(t, GeneratedStale, classifyFragment(older, want))
	assert.Equal(t, GeneratedHandEdited, classifyFragment(strings.Replace(want, "row two", "row 2", 1), want))
	assert.Equal(t, GeneratedHandEdited, classifyFragment("\nno hash line\n", want))
	assert.Equal(t, GeneratedHandEdited, classifyFragment("", want))
}

func TestRecognisedKBComment_AcceptsExactlyTheFourShapes(t *testing.T) {
	for _, ok := range []string{
		"<!-- kb:anchor sessions.pin -->",
		"<!-- kb:generated 0123456789abcdef — regenerated by make gen-kb; edit the sources, not this file -->",
		"<!-- kb:features -->", "<!-- /kb:features -->", "<!-- kb:trailer -->", "<!-- /kb:trailer -->",
		"<!-- kb:hash 0123456789abcdef -->",
	} {
		assert.True(t, recognisedKBComment(ok), ok)
	}
	for _, bad := range []string{
		"<!-- kb:anchors -->", "<!-- kb:anchor Bad_Id -->", "<!-- kb:generated short -->",
		"<!-- kb:index -->", "<!-- kb:hash xyz -->", "<!-- kb:pack plan=x -->",
	} {
		assert.False(t, recognisedKBComment(bad), bad)
	}
}
